nodeLinker: node-modules

npmMinimalAgeGate: 14d

npmPreapprovedPackages: []

npmScopes:
  mobiscroll:
    npmAuthToken: zh18sg3QSUbz/ujpeXzCdKq1J6QEOJw5B4PwnJ9pWT5Gt0P5f8b60Jzh7iX1FhwSxL7EyIr7YcoB+H/t1HQs8w==
    npmRegistryServer: "https://npm.mobiscroll.com"